<?php
if( function_exists('acf_add_local_field_group') ):

	acf_add_local_field_group(array(
		'key' => 'group_5c8117e9d3baa',
		'title' => 'Migration Options',
		'fields' => array(
			array(
				'key' => 'field_5c8673d2b5c1f',
				'label' => 'Categories',
				'name' => 'fd-category',
				'type' => 'taxonomy',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'taxonomy' => 'category',
				'field_type' => 'radio',
				'allow_null' => 0,
				'add_term' => 1,
				'save_terms' => 0,
				'load_terms' => 0,
				'return_format' => 'id',
				'multiple' => 0,
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'page',
				),
			),
		),
		'menu_order' => 1,
		'position' => 'side',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));

endif;

if( function_exists('acf_add_local_field_group') ):

	acf_add_local_field_group(array(
		'key' => 'group_5b9ffbc61808a',
		'title' => 'категории',
		'fields' => array(
			array(
				'key' => 'field_5b48c7337143f',
				'label' => 'табы',
				'name' => 'tabs',
				'type' => 'textarea',
				'instructions' => '/ tabs',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => 6,
				'new_lines' => '',
			),
			array(
				'key' => 'field_5ad0741e2a54d',
				'label' => 'заголовок',
				'name' => 'header1',
				'type' => 'text',
				'instructions' => '/ header1',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5b5ded71732fb',
				'label' => 'подзаголовок',
				'name' => 'subhead',
				'type' => 'text',
				'instructions' => '/ subhead',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5b5cdce9891ef',
				'label' => 'Юрлицо',
				'name' => 'legal',
				'type' => 'text',
				'instructions' => '/ legal',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5b6f591cade7b',
				'label' => 'реестр',
				'name' => 'reestr',
				'type' => 'text',
				'instructions' => '/ reestr',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5af4388b4a360',
				'label' => 'орг форма',
				'name' => 'org',
				'type' => 'radio',
				'instructions' => '/ org',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'mfk' => 'МФК',
					'mkk' => 'МКК',
					'broker' => 'Кредитный брокер',
					'bank' => 'Банк',
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'default_value' => '',
				'layout' => 'horizontal',
				'return_format' => 'value',
				'save_other_choice' => 0,
			),
			array(
				'key' => 'field_5af437c968182',
				'label' => 'тип',
				'name' => 'type',
				'type' => 'radio',
				'instructions' => '/ type',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5af4388b4a360',
							'operator' => '==',
							'value' => 'mfk',
						),
					),
					array(
						array(
							'field' => 'field_5af4388b4a360',
							'operator' => '==',
							'value' => 'mkk',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'online' => 'Онлайн',
					'offline' => 'Офлайн',
					'hybrid' => 'Гибрид (офлайн + онлайн)',
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'default_value' => '',
				'layout' => 'horizontal',
				'return_format' => 'value',
				'save_other_choice' => 0,
			),
			array(
				'key' => 'field_5bcde60daafc3',
				'label' => 'Гео',
				'name' => 'geo',
				'type' => 'checkbox',
				'instructions' => '/ geo',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'rus' => 'по всей России',
					'msk' => 'Москва',
					'mo' => 'Московская обл.',
					'spb' => 'Санкт-Петербург',
					'len' => 'Ленинградская обл.',
				),
				'allow_custom' => 1,
				'save_custom' => 1,
				'default_value' => array(
				),
				'layout' => 'horizontal',
				'toggle' => 0,
				'return_format' => 'label',
			),
			array(
				'key' => 'field_5be061d56e27d',
				'label' => 'Гео (дополнительно)',
				'name' => 'geo_custom',
				'type' => 'text',
				'instructions' => '/ geo_custom',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5ac760b58579d',
				'label' => 'Срок займа ОТ',
				'name' => 'srok_ot',
				'type' => 'number',
				'instructions' => '/ srok_ot',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => 'от',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array(
				'key' => 'field_5ac762106e5eb',
				'label' => 'Срок займа ДО',
				'name' => 'srok_do',
				'type' => 'number',
				'instructions' => '/ srok_do',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => 'до',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array(
				'key' => 'field_5c2637420840d',
				'label' => 'Сумма займа ОТ',
				'name' => 'summa_ot',
				'type' => 'number',
				'instructions' => '/ summa_ot',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => 'от',
				'append' => 'рублей',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array(
				'key' => 'field_5ac760fc8579e',
				'label' => 'Сумма займа ДО',
				'name' => 'summa',
				'type' => 'number',
				'instructions' => '/ summa',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => 'до',
				'append' => 'рублей',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array(
				'key' => 'field_5b5df11b255c0',
				'label' => 'MIN ставка',
				'name' => 'min_stavka',
				'type' => 'true_false',
				'instructions' => 'Есть ли нижняя планка ставки / min_stavka',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_5b5cd602724f4',
				'label' => 'Процентная ставка ОТ',
				'name' => 'stavka_ot',
				'type' => 'number',
				'instructions' => 'минимально возможная ставка / stavka_ot',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5b5df11b255c0',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => 'от',
				'append' => '%',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array(
				'key' => 'field_5ac76265e2beb',
				'label' => 'Процентная ставка ДО',
				'name' => 'stavka',
				'type' => 'number',
				'instructions' => 'максимальная ставка в день / stavka',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => 'до',
				'append' => '% в день',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array(
				'key' => 'field_5c4c2706262cb',
				'label' => 'ПСК ОТ',
				'name' => 'psk_ot',
				'type' => 'number',
				'instructions' => 'ПСК минимальная / psk_ot',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5b5df11b255c0',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => 'от',
				'append' => '%',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array(
				'key' => 'field_5c4c2732262cc',
				'label' => 'ПСК ДО',
				'name' => 'psk',
				'type' => 'number',
				'instructions' => 'ПСК максимальная / psk',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => 'до',
				'append' => '% годовых',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array(
				'key' => 'field_5b5cd23335f7a',
				'label' => 'Первый займ лимит ДО',
				'name' => 'first_summa',
				'type' => 'number',
				'instructions' => 'Макс сумма для нового клиента / first_summa',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => 'до',
				'append' => 'рублей',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array(
				'key' => 'field_5b854239b12a6',
				'label' => 'Первый займ срок ДО',
				'name' => 'first_srok',
				'type' => 'number',
				'instructions' => '/ first_srok',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => 'от',
				'append' => 'дней',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array(
				'key' => 'field_5ac762bbe2bed',
				'label' => 'Займ 0%',
				'name' => 'first_zaim',
				'type' => 'true_false',
				'instructions' => 'есть ли первый займ бесплатно / first_zaim',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_5c2639070840f',
				'label' => 'Займ 0% лимит ДО',
				'name' => 'first_zero_limit',
				'type' => 'number',
				'instructions' => 'максимальная сумма для нового клиента / first_zero_limit',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5ac762bbe2bed',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => 'до',
				'append' => 'рублей',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array(
				'key' => 'field_5c2639020840e',
				'label' => 'Займ 0% срок ДО',
				'name' => 'first_zero_srok',
				'type' => 'number',
				'instructions' => '/ first_zero_srok',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5ac762bbe2bed',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => 'до',
				'append' => 'дней',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array(
				'key' => 'field_5b98d154e8683',
				'label' => 'Долгосрочный займ',
				'name' => 'dolgosrok',
				'type' => 'true_false',
				'instructions' => 'есть ли долгосрочные тарифы > 1 месяца / dolgosrok',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_5b98dc46b9c80',
				'label' => 'Долгосрок доступность',
				'name' => 'dolgosrok_able',
				'type' => 'radio',
				'instructions' => '/ dolgosrok_able',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5b98d154e8683',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'srazu' => 'с первого обращения',
					'later' => 'при повторном обращении',
					'personal' => 'персональное предложение (программа лояльности)',
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'default_value' => '',
				'layout' => 'horizontal',
				'return_format' => 'label',
				'save_other_choice' => 0,
			),
			array(
				'key' => 'field_5b98d35470d32',
				'label' => 'Долгосрок срок займа ОТ',
				'name' => 'dolgosrok_ot',
				'type' => 'number',
				'instructions' => '/ dolgosrok_ot',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5b98d154e8683',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => 'от',
				'append' => 'месяцев',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array(
				'key' => 'field_5b98d37a70d33',
				'label' => 'Долгосрок срок займа ДО',
				'name' => 'dolgosrok_do',
				'type' => 'number',
				'instructions' => '/ dolgosrok_do',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5b98d154e8683',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => 'до',
				'append' => 'месяцев',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array(
				'key' => 'field_5b98d3c470d34',
				'label' => 'Долгосрок лимит займа ДО',
				'name' => 'dolgosrok_summa',
				'type' => 'number',
				'instructions' => '/ dolgosrok_summa',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5b98d154e8683',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => 'до',
				'append' => 'рублей',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array(
				'key' => 'field_5b98dbdda8946',
				'label' => 'Долгосрок MIN ставка',
				'name' => 'dolgosrok_min_stavka',
				'type' => 'true_false',
				'instructions' => 'есть ли минимальная планка по ставке / dolgosrok_min_stavka',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5b98d154e8683',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_5b98d41370d35',
				'label' => 'Долгосрок процентная ставка ОТ',
				'name' => 'dolgosrok_stavka_ot',
				'type' => 'number',
				'instructions' => '/ dolgosrok_stavka_ot',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5b98d154e8683',
							'operator' => '==',
							'value' => '1',
						),
						array(
							'field' => 'field_5b98dbdda8946',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => 'от',
				'append' => '%',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array(
				'key' => 'field_5b98d44770d36',
				'label' => 'Долгосрок процентная ставка ДО',
				'name' => 'dolgosrok_stavka',
				'type' => 'number',
				'instructions' => 'максимальная / dolgosrok_stavka',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5b98d154e8683',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => 'до',
				'append' => '%',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array(
				'key' => 'field_5b98d46d70d37',
				'label' => 'Платежи',
				'name' => 'payments_dolgosrok',
				'type' => 'radio',
				'instructions' => '/ payments_dolgosrok',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5b98d154e8683',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'weekly' => 'еженедельно',
					'2weekly' => 'раз в 2 недели',
					'monthly' => 'ежемесячно',
					'choose' => '1 или 2 раза в месяц',
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'default_value' => '',
				'layout' => 'horizontal',
				'return_format' => 'label',
				'save_other_choice' => 0,
			),
			array(
				'key' => 'field_5be0117080a0f',
				'label' => '% одобрения долгосрок',
				'name' => 'approve_dolgosrok',
				'type' => 'radio',
				'instructions' => '/ approve_dolgosrok',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5b98d154e8683',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'low' => '<mark style="background: #fbede996;"><span style="font-weight:bold;color:#664040;">низкий</span> (нужна хорошая КИ)</mark>',
					'mid' => '<mark style="background: #b4a35812;"><span style="font-weight:bold;color:#555;">средний</span> (минимум просрочек в КИ)</mark>',
					'hi' => '<mark style="background: #e9f9ed54;"><span style="font-weight:bold;color:#2e6613;">высокий</span> (допустима КИ с просрочками)</mark>',
					'vhi' => '<mark style="background: #e9f9ed54;"><span style="font-weight:bold;color:#2e6613;">очень высокий</span> (без отказов, не смотрят КИ)</mark>',
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'default_value' => '',
				'layout' => 'horizontal',
				'return_format' => 'label',
				'save_other_choice' => 0,
			),
			array(
				'key' => 'field_5b5cd27b35f7b',
				'label' => '% одобрения',
				'name' => 'approve',
				'type' => 'radio',
				'instructions' => '/ approve',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'low' => '<mark style="background: #fbede996;"><span style="font-weight:bold;color:#664040;">низкий</span> (нужна хорошая КИ)</mark>',
					'mid' => '<mark style="background: #b4a35812;"><span style="font-weight:bold;color:#555;">средний</span> (минимум просрочек в КИ)</mark>',
					'hi' => '<mark style="background: #e9f9ed54;"><span style="font-weight:bold;color:#2e6613;">высокий</span> (допустима КИ с просрочками)</mark>',
					'vhi' => '<mark style="background: #e9f9ed54;"><span style="font-weight:bold;color:#2e6613;">очень высокий</span> (без отказов, не смотрят КИ)</mark>',
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'default_value' => '',
				'layout' => 'horizontal',
				'return_format' => 'label',
				'save_other_choice' => 0,
			),
			array(
				'key' => 'field_5b5db7fc49a0b',
				'label' => 'Возраст ОТ',
				'name' => 'age',
				'type' => 'number',
				'instructions' => '/ age',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '30',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => 'от',
				'append' => 'лет',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array(
				'key' => 'field_5b7e807ec092f',
				'label' => 'Возраст ДО',
				'name' => 'age_max',
				'type' => 'number',
				'instructions' => '/ age_max',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '30',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => 'до',
				'append' => 'лет',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array(
				'key' => 'field_5b5cdf75bbe3f',
				'label' => 'на карту',
				'name' => 'na_kartu',
				'type' => 'checkbox',
				'instructions' => '/ na_kartu',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'visa' => '&#x1F4B3;&nbsp;на карту (VISA, Mastercard',
					'mir' => 'МИР',
					'account' => 'счёт',
				),
				'allow_custom' => 0,
				'default_value' => array(
				),
				'layout' => 'vertical',
				'toggle' => 0,
				'return_format' => 'label',
				'save_custom' => 0,
			),
			array(
				'key' => 'field_5b5ce02abbe40',
				'label' => 'эл кошельки',
				'name' => 'wallet',
				'type' => 'checkbox',
				'instructions' => '/ wallet',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'qiwi' => '&#x1F4B0;&nbsp;на&nbsp;QIWI Кошелек',
					'yd' => 'Яндекс.Деньги',
				),
				'allow_custom' => 0,
				'default_value' => array(
				),
				'layout' => 'vertical',
				'toggle' => 0,
				'return_format' => 'label',
				'save_custom' => 0,
			),
			array(
				'key' => 'field_5bdec2f1b4f10',
				'label' => 'эл деньги условия',
				'name' => 'wallet_cond',
				'type' => 'select',
				'instructions' => '/ wallet_cond',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5b5ce02abbe40',
							'operator' => '!=empty',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'karta' => '(требуется регистрация карты)',
					'no' => '(без привязки карты)',
				),
				'default_value' => array(
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'label',
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_5b5ce097bbe41',
				'label' => 'Наличными',
				'name' => 'nal',
				'type' => 'checkbox',
				'instructions' => '/ nal',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'uni' => 'Юнистрим',
					'korona' => 'Золотая Корона',
					'contact' => 'Contact',
					'office' => '&#x1F4B6;&nbsp;наличными',
				),
				'allow_custom' => 0,
				'default_value' => array(
				),
				'layout' => 'vertical',
				'toggle' => 0,
				'return_format' => 'label',
				'save_custom' => 0,
			),
			array(
				'key' => 'field_5bef0c85e1755',
				'label' => 'Наличными условия получения',
				'name' => 'nal_cond',
				'type' => 'select',
				'instructions' => '/ nal_cond',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5b5ce097bbe41',
							'operator' => '!=empty',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'karta' => '(нужна именная карта)',
					'no' => '(карта не требуется)',
				),
				'default_value' => array(
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'label',
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_5ac76354c90fe',
				'label' => 'Время работы',
				'name' => 'time',
				'type' => 'radio',
				'instructions' => '/ time',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					24 => 'круглосуточно',
					'partly' => 'рассмотрение круглосуточно, перевод в рабочие часы',
					'day' => '&#x1F552;',
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'default_value' => 'да',
				'layout' => 'horizontal',
				'return_format' => 'label',
				'save_other_choice' => 0,
			),
			array(
				'key' => 'field_5bdea2ee663e1',
				'label' => 'Рабочее время',
				'name' => 'workhours',
				'type' => 'text',
				'instructions' => '/ workhours',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5ac76354c90fe',
							'operator' => '==',
							'value' => 'day',
						),
					),
					array(
						array(
							'field' => 'field_5ac76354c90fe',
							'operator' => '==',
							'value' => 'partly',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5bdea34e663e2',
				'label' => 'Скорость и тип рассмотрения заявки (текст)',
				'name' => 'zayavkast',
				'type' => 'text',
				'instructions' => '/ zayavkast',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5c2905b419488',
				'label' => 'Тип рассмотрения заявки',
				'name' => 'zayavkast_type',
				'type' => 'select',
				'instructions' => '/ zayavkast_type',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5b5ce097bbe41',
							'operator' => '!=empty',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'auto' => 'Автоматически',
					'cond' => 'Автоматически (возможна ручная проверка)',
					'manual' => 'Ручная проверка',
				),
				'default_value' => array(
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'label',
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_5c29066419489',
				'label' => 'Скорость рассмотрения заявки ОТ',
				'name' => 'zayavkast_number_ot',
				'type' => 'number',
				'instructions' => '/ zayavkast_number_ot',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5c2905b419488',
							'operator' => '==',
							'value' => 'cond',
						),
					),
					array(
						array(
							'field' => 'field_5c2905b419488',
							'operator' => '==',
							'value' => 'manual',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => 'до',
				'append' => 'минут',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array(
				'key' => 'field_5c2904e819487',
				'label' => 'Скорость рассмотрения заявки ДО',
				'name' => 'zayavkast_number',
				'type' => 'number',
				'instructions' => '/ zayavkast_number',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => 'до',
				'append' => 'минут',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array(
				'key' => 'field_5b4a0d6a135ec',
				'label' => 'Услуга "кредитный рейтинг" в ЛК',
				'name' => 'kreditrate',
				'type' => 'radio',
				'instructions' => '/ kreditrate',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'none' => 'нет',
					'paid' => 'платно',
					'free' => 'бесплатно',
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'default_value' => 'none',
				'layout' => 'horizontal',
				'return_format' => 'value',
				'save_other_choice' => 0,
			),
			array(
				'key' => 'field_5b8507606e6e8',
				'label' => 'Требуемый кредитный рейтинг',
				'name' => 'kred_rating',
				'type' => 'text',
				'instructions' => 'минимальный - максимальный / kred_rating',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5bc08e575206a',
				'label' => 'Требования к заемщику КИ',
				'name' => 'demand',
				'type' => 'select',
				'instructions' => '/ demand',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'unknown' => '',
					'yes' => 'требуется хорошая КИ, минимум просрочек',
					'mid' => 'допустима КИ с просрочками',
					'no' => 'не смотрят (допустима проблемная КИ)',
				),
				'default_value' => array(
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'label',
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_5bc71a77e6416',
				'label' => 'Анкета',
				'name' => 'anketa',
				'type' => 'checkbox',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'pass' => 'паспортные данные',
					'snils' => 'СНИЛС',
					'tel' => 'телефон',
					'card' => 'именная карта',
					'contacts' => 'номера контактных лиц',
					'work' => 'сведения о работе и доходах',
					'credits' => 'кредитная история',
					'gosuslugi' => 'доступна регистрация через Госуслуги',
				),
				'allow_custom' => 0,
				'default_value' => array(
					0 => '/ anketa',
				),
				'layout' => 'horizontal',
				'toggle' => 0,
				'return_format' => 'label',
				'save_custom' => 0,
			),
			array(
				'key' => 'field_5bc08dd052069',
				'label' => 'Сканы	и фото документов',
				'name' => 'documents',
				'type' => 'checkbox',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'docs' => 'сканы паспорта',
					'card' => 'фото именной карты',
					'selfie' => 'личное фото с паспортом',
					'video' => 'лично в офисе с паспортом',
					'no' => 'не требуют фото документов',
				),
				'allow_custom' => 0,
				'default_value' => array(
					0 => '/ documents',
				),
				'layout' => 'horizontal',
				'toggle' => 0,
				'return_format' => 'label',
				'save_custom' => 0,
			),
			array(
				'key' => 'field_5bc754e8649db',
				'label' => 'опции документов',
				'name' => 'options_doc',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5bc08dd052069',
							'operator' => '>',
							'value' => '0',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'none' => '',
					'must' => '&nbsp;',
					'opt' => '(по запросу)',
				),
				'default_value' => array(
					0 => '1 - нет 2 - обязательно 3 - по запросу	/ options_doc',
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'label',
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_5bc08d6152068',
				'label' => 'Звонят операторы после заявки?',
				'name' => 'nocall',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'unknown' => '',
					'yes' => 'по номеру телефона',
					'yessome' => 'могут позвонить для сверки данных',
					'yesplus' => 'контактным лицам и на работу',
					'yesboth' => 'на личный номер и контактным лицам',
					'no' => 'не звонят',
				),
				'default_value' => array(
					0 => '/ nocall',
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'label',
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_5bc736125e51c',
				'label' => 'Дополнительное (если есть что добавить)',
				'name' => 'extra',
				'type' => 'text',
				'instructions' => '/ extra',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5bae01af61f8e',
				'label' => 'надежность',
				'name' => 'trust',
				'type' => 'select',
				'instructions' => '1 Нет инфы
2 Надежная (не сливают)
3 Ненадежная (сливают)
/ trust',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'noinfo' => 'нет информации',
					'yes' => 'Надежная (не сливают)',
					'no' => 'Ненадежная (сливают)',
				),
				'default_value' => array(
					0 => 'noinfo',
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_5ac76287e2bec',
				'label' => 'Рейтинг компании',
				'name' => 'rating',
				'type' => 'number',
				'instructions' => '3-3,5 низкий	- для офлайн и очень плохих онлайн
3,7 - 4 - средний 
от 4,2 - хорошая компания
/ rating',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => 'rating',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array(
				'key' => 'field_5b5cdd04891f0',
				'label' => 'Партнерская ссылка (основная)',
				'name' => 'aff',
				'type' => 'text',
				'instructions' => '/ aff',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5c25c8d292a58',
				'label' => 'альтернативная ссылка',
				'name' => 'aff_alt',
				'type' => 'text',
				'instructions' => '1 сюда как добавляется ссылка без рефки напрямую. нужно в случае если рекл отключает оффер
2 второй вариант когда у компании есть несколько разных офферов, например займы до зп и займы долгосрок
/ aff_alt',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5c25c8a192a57',
				'label' => 'переключить рефку на альтернативу ссылку',
				'name' => 'aff_alt_on',
				'type' => 'true_false',
				'instructions' => '/ aff_alt_on',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_5b7e83713146d',
				'label' => 'Промокоды',
				'name' => 'promokod',
				'type' => 'true_false',
				'instructions' => '/ promokod',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_5b7e84cc3146e',
				'label' => 'Текст промокода',
				'name' => 'promo_text',
				'type' => 'text',
				'instructions' => '/ promo_text',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5b7e83713146d',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5b8173c4cea42',
				'label' => 'промокод описание',
				'name' => 'promo_esc',
				'type' => 'text',
				'instructions' => '/ promo_esc',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5b7e83713146d',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5b7e90f76ac71',
				'label' => 'Промокод дата окончания',
				'name' => 'promo_date',
				'type' => 'date_picker',
				'instructions' => '/ promo_date',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5b7e83713146d',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'display_format' => 'd/m/Y',
				'save_format' => 'yymmdd',
				'first_day' => 1,
				'return_format' => 'd/m/Y',
			),
			array(
				'key' => 'field_5b7e86313146f',
				'label' => 'Акции, скидки',
				'name' => 'actions',
				'type' => 'true_false',
				'instructions' => '/ actions',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_5b7e864e31470',
				'label' => 'Акции текстовое поле',
				'name' => 'akcii_text',
				'type' => 'textarea',
				'instructions' => '/ akcii_text',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5b7e86313146f',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => 4,
				'new_lines' => '',
			),
			array(
				'key' => 'field_5b7e9a5b1edda',
				'label' => 'Акция дата окончания',
				'name' => 'akcii_date',
				'type' => 'date_picker',
				'instructions' => '/ akcii_date',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5b7e86313146f',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'display_format' => 'd/m/Y',
				'save_format' => 'yymmdd',
				'first_day' => 1,
				'return_format' => 'd/m/Y',
			),
			array(
				'key' => 'field_5c264772c6d59',
				'label' => 'Листинги',
				'name' => 'listingi',
				'type' => 'checkbox',
				'instructions' => '/ listingi',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'main' => 'Главная (/)',
					'mfo' => 'Рейтинг онлайн займов (/mfo)',
					'karta' => 'На карту',
					'schet' => 'На счет',
					'qiwi' => 'На QIWI',
					'yandex' => 'На Яндекс',
					'zero' => 'Под 0%',
					'nal' => 'Наличными',
					'korona' => 'Корона',
					'dolgosrok' => 'Долгосрочные',
					'bezotkaz' => 'Без отказа',
					'nocall' => 'Без звонков',
					'kruglosutochno' => 'Круглосуточно',
					'mgnovenno' => 'Мгновенно',
					'vigodnie' => 'Выгодные',
					'pensioneram' => 'Пенсионерам',
					'pod_zalog' => 'Под залог',
				),
				'allow_custom' => 1,
				'save_custom' => 1,
				'default_value' => array(
				),
				'layout' => 'horizontal',
				'toggle' => 0,
				'return_format' => 'value',
			),
			array(
				'key' => 'field_5c2659aaddc22',
				'label' => 'Убрать со всех листингов',
				'name' => 'listingi_off',
				'type' => 'true_false',
				'instructions' => '/ listingi_off',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_5b85181c1fd66',
				'label' => 'Резюме (рейтинг займов)',
				'name' => 'resume',
				'type' => 'text',
				'instructions' => '/ resume',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5b86b4af26edf',
				'label' => 'Особенности (рейтинг займов)',
				'name' => 'feat_rate',
				'type' => 'textarea',
				'instructions' => '/ feat_rate',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => 8,
				'new_lines' => '',
			),
			array(
				'key' => 'field_5b9234896148a',
				'label' => 'Резюме	(0%)',
				'name' => 'resume_zero',
				'type' => 'text',
				'instructions' => '/ resume_zero',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5ac762bbe2bed',
							'operator' => '==',
							'value' => '1',
						),
					),
					array(
						array(
							'field' => 'field_5c264772c6d59',
							'operator' => '==',
							'value' => 'zero',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5b85153bf8d46',
				'label' => 'Особенности список (0%)',
				'name' => 'feat',
				'type' => 'textarea',
				'instructions' => '/ feat',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5ac762bbe2bed',
							'operator' => '==',
							'value' => '1',
						),
					),
					array(
						array(
							'field' => 'field_5c264772c6d59',
							'operator' => '==',
							'value' => 'zero',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => 8,
				'new_lines' => '',
			),
			array(
				'key' => 'field_5b923d25a537d',
				'label' => 'Резюме (QIWI)',
				'name' => 'resume_qiwi',
				'type' => 'text',
				'instructions' => '/ resume_qiwi',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5b5ce02abbe40',
							'operator' => '==',
							'value' => 'qiwi',
						),
					),
					array(
						array(
							'field' => 'field_5c264772c6d59',
							'operator' => '==',
							'value' => 'qiwi',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5b9235106148c',
				'label' => 'Особенности (QIWI)',
				'name' => 'feat_qiwi',
				'type' => 'textarea',
				'instructions' => '/ feat_qiwi',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5b5ce02abbe40',
							'operator' => '==',
							'value' => 'qiwi',
						),
					),
					array(
						array(
							'field' => 'field_5c264772c6d59',
							'operator' => '==',
							'value' => 'qiwi',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => 8,
				'new_lines' => '',
			),
			array(
				'key' => 'field_5bf83ad7382e5',
				'label' => 'Резюме (ЯД)',
				'name' => 'resume_yd',
				'type' => 'text',
				'instructions' => '/ resume_yd',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5b5ce02abbe40',
							'operator' => '==',
							'value' => 'yd',
						),
					),
					array(
						array(
							'field' => 'field_5c264772c6d59',
							'operator' => '==',
							'value' => 'yandex',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5b92362cae71b',
				'label' => 'Резюме (наличные)',
				'name' => 'resume_cash',
				'type' => 'text',
				'instructions' => '/ resume_cash',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5b5ce097bbe41',
							'operator' => '==',
							'value' => 'contact',
						),
					),
					array(
						array(
							'field' => 'field_5b5ce097bbe41',
							'operator' => '==',
							'value' => 'office',
						),
					),
					array(
						array(
							'field' => 'field_5c264772c6d59',
							'operator' => '==',
							'value' => 'nal',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5b923650ae71d',
				'label' => 'Особенности (наличные)',
				'name' => 'feat_cash',
				'type' => 'textarea',
				'instructions' => '/ feat_cash',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5b5ce097bbe41',
							'operator' => '==',
							'value' => 'contact',
						),
					),
					array(
						array(
							'field' => 'field_5b5ce097bbe41',
							'operator' => '==',
							'value' => 'office',
						),
					),
					array(
						array(
							'field' => 'field_5c264772c6d59',
							'operator' => '==',
							'value' => 'nal',
						),
					),
					array(
						array(
							'field' => 'field_5b5ce097bbe41',
							'operator' => '==',
							'value' => 'korona',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => 8,
				'new_lines' => '',
			),
			array(
				'key' => 'field_5c0bcf4dc580d',
				'label' => 'Резюме (Корона)',
				'name' => 'resume_korona',
				'type' => 'text',
				'instructions' => '/ resume_korona',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5b5ce097bbe41',
							'operator' => '==',
							'value' => 'korona',
						),
					),
					array(
						array(
							'field' => 'field_5c264772c6d59',
							'operator' => '==',
							'value' => 'korona',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5b9234fa6148b',
				'label' => 'Резюме (Карта)',
				'name' => 'resume_karta',
				'type' => 'text',
				'instructions' => '/ resume_karta',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5b5cdf75bbe3f',
							'operator' => '==',
							'value' => 'visa',
						),
					),
					array(
						array(
							'field' => 'field_5c264772c6d59',
							'operator' => '==',
							'value' => 'karta',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5c66656397fc5',
				'label' => 'Резюме (счет)',
				'name' => 'resume_schet',
				'type' => 'text',
				'instructions' => '/ resume_schet',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5b5cdf75bbe3f',
							'operator' => '==',
							'value' => 'account',
						),
					),
					array(
						array(
							'field' => 'field_5c264772c6d59',
							'operator' => '==',
							'value' => 'schet',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5b9235a8ae71a',
				'label' => 'Особенности (Карта)',
				'name' => 'feat_karta',
				'type' => 'textarea',
				'instructions' => '/ feat_karta',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5b5cdf75bbe3f',
							'operator' => '==',
							'value' => 'visa',
						),
					),
					array(
						array(
							'field' => 'field_5c264772c6d59',
							'operator' => '==',
							'value' => 'karta',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => 8,
				'new_lines' => '',
			),
			array(
				'key' => 'field_5b98d09ce8681',
				'label' => 'Резюме (долгосрок)',
				'name' => 'resume_dolgosrok',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5b98d154e8683',
							'operator' => '==',
							'value' => '1',
						),
					),
					array(
						array(
							'field' => 'field_5c264772c6d59',
							'operator' => '==',
							'value' => 'dolgosrok',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5b98d0c6e8682',
				'label' => 'Особенности (долгосрок)',
				'name' => 'feat_dolgosrok',
				'type' => 'textarea',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5b98d154e8683',
							'operator' => '==',
							'value' => '1',
						),
					),
					array(
						array(
							'field' => 'field_5c264772c6d59',
							'operator' => '==',
							'value' => 'dolgosrok',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => 8,
				'new_lines' => '',
			),
			array(
				'key' => 'field_5bba60adc2cd9',
				'label' => 'Резюме (без отказа)',
				'name' => 'resume_bezotkaz',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5c264772c6d59',
							'operator' => '==',
							'value' => 'bezotkaz',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5bba60dac2cda',
				'label' => 'Особенности (без отказа)',
				'name' => 'feat_bezotkaz',
				'type' => 'textarea',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5c264772c6d59',
							'operator' => '==',
							'value' => 'bezotkaz',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => 8,
				'new_lines' => '',
			),
			array(
				'key' => 'field_5c0d0d3253d74',
				'label' => 'Резюме (круглосуточно)',
				'name' => 'resume_kruglosutochno',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5ac76354c90fe',
							'operator' => '==',
							'value' => '24',
						),
					),
					array(
						array(
							'field' => 'field_5c264772c6d59',
							'operator' => '==',
							'value' => 'kruglosutochno',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5c2903de19485',
				'label' => 'Резюме мгновенно',
				'name' => 'resume_mgnovenno',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5c264772c6d59',
							'operator' => '==',
							'value' => 'mgnovenno',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5c1bccb8bbffb',
				'label' => 'Резюме (выгодные)',
				'name' => 'resume_vigodnie',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5c264772c6d59',
							'operator' => '==',
							'value' => 'vigodnie',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5c1bd2ceaf8c7',
				'label' => 'Особенности (выгодные)',
				'name' => 'feat_vigodnie',
				'type' => 'textarea',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5c264772c6d59',
							'operator' => '==',
							'value' => 'vigodnie',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => 8,
				'new_lines' => '',
			),
			array(
				'key' => 'field_5bc0750bd1ad3',
				'label' => 'Без звонков',
				'name' => 'bez_zvonkov',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_5bc07555d1ad4',
				'label' => 'Резюме (без звонков)',
				'name' => 'resume_bez_zvonkov',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5bc0750bd1ad3',
							'operator' => '==',
							'value' => '1',
						),
					),
					array(
						array(
							'field' => 'field_5c264772c6d59',
							'operator' => '==',
							'value' => 'nocall',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5bc0758cd1ad9',
				'label' => 'Особенности (без звонков)',
				'name' => 'feat_bez_zvonkov',
				'type' => 'textarea',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5bc0750bd1ad3',
							'operator' => '==',
							'value' => '1',
						),
					),
					array(
						array(
							'field' => 'field_5c264772c6d59',
							'operator' => '==',
							'value' => 'nocall',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'new_lines' => '',
			),
			array(
				'key' => 'field_5c0ec23aecb3c',
				'label' => 'Резюме (пенсионерам)',
				'name' => 'resume_pens',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5c264772c6d59',
							'operator' => '==',
							'value' => 'pensioneram',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5bbb6b03b9fcb',
				'label' => 'Под залог',
				'name' => 'zalog',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_5bbb6b18b9fcc',
				'label' => 'Тип залога',
				'name' => 'tip_zalog',
				'type' => 'radio',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5bbb6b03b9fcb',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'avto' => 'Авто',
					'estate' => 'Недвижимость',
					'zalog_all' => 'Оба варианта',
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'default_value' => '',
				'layout' => 'horizontal',
				'return_format' => 'value',
				'save_other_choice' => 0,
			),
			array(
				'key' => 'field_5bd17bdb59042',
				'label' => 'Резюме (под залог)',
				'name' => 'resume_zalog',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5bbb6b03b9fcb',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5bd17c1f59043',
				'label' => 'Особенности (под залог)',
				'name' => 'feat_zalog',
				'type' => 'textarea',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5bbb6b03b9fcb',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'new_lines' => '',
			),
			array(
				'key' => 'field_5bbb6a6bb9fc9',
				'label' => 'Краткое резюме залог авто',
				'name' => 'resume_avto',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5bbb6b18b9fcc',
							'operator' => '==',
							'value' => 'avto',
						),
						array(
							'field' => 'field_5bbb6b03b9fcb',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5bbb6a90b9fca',
				'label' => 'Особенности список залог авто',
				'name' => 'feat_avto',
				'type' => 'textarea',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5bbb6b03b9fcb',
							'operator' => '==',
							'value' => '1',
						),
						array(
							'field' => 'field_5bbb6b18b9fcc',
							'operator' => '==',
							'value' => 'avto',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'new_lines' => '',
			),
			array(
				'key' => 'field_5bbb6d37b4ce3',
				'label' => 'под залог авто ставка ОТ',
				'name' => 'avto_stavka_ot',
				'type' => 'number',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5bbb6b03b9fcb',
							'operator' => '==',
							'value' => '1',
						),
						array(
							'field' => 'field_5bbb6b18b9fcc',
							'operator' => '==',
							'value' => 'avto',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array(
				'key' => 'field_5bbb6d8fb4ce4',
				'label' => 'под залог авто ставка ДО',
				'name' => 'avto_stavka_do',
				'type' => 'number',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5bbb6b03b9fcb',
							'operator' => '==',
							'value' => '1',
						),
						array(
							'field' => 'field_5bbb6b18b9fcc',
							'operator' => '==',
							'value' => 'avto',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array(
				'key' => 'field_5bbb6e21b4ce8',
				'label' => 'авто Сумма займа ОТ',
				'name' => 'avto_sum_ot',
				'type' => 'number',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5bbb6b03b9fcb',
							'operator' => '==',
							'value' => '1',
						),
						array(
							'field' => 'field_5bbb6b18b9fcc',
							'operator' => '==',
							'value' => 'avto',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => 'до',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array(
				'key' => 'field_5bbb6dbfb4ce5',
				'label' => 'авто сумма	займа ДО',
				'name' => 'avto_sum_do',
				'type' => 'number',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5bbb6b03b9fcb',
							'operator' => '==',
							'value' => '1',
						),
						array(
							'field' => 'field_5bbb6b18b9fcc',
							'operator' => '==',
							'value' => 'avto',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => 'до',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array(
				'key' => 'field_5bbb6e5cb4cea',
				'label' => 'авто срок займа ОТ',
				'name' => 'avto_srok_ot',
				'type' => 'number',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5bbb6b03b9fcb',
							'operator' => '==',
							'value' => '1',
						),
						array(
							'field' => 'field_5bbb6b18b9fcc',
							'operator' => '==',
							'value' => 'avto',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => 'до',
				'append' => 'месяцев',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array(
				'key' => 'field_5bbb6e35b4ce9',
				'label' => 'авто срок займа ДО',
				'name' => 'avto_srok_do',
				'type' => 'number',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5bbb6b03b9fcb',
							'operator' => '==',
							'value' => '1',
						),
						array(
							'field' => 'field_5bbb6b18b9fcc',
							'operator' => '==',
							'value' => 'avto',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => 'до',
				'append' => 'месяцев',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array(
				'key' => 'field_5bd6df60d1e41',
				'label' => 'Резюме (недвиж)',
				'name' => 'resume_estate',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5bbb6b18b9fcc',
							'operator' => '==',
							'value' => 'estate',
						),
						array(
							'field' => 'field_5bbb6b03b9fcb',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5bd6df66d1e42',
				'label' => 'Особенности (недвиж)',
				'name' => 'feat_estate',
				'type' => 'textarea',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5bbb6b03b9fcb',
							'operator' => '==',
							'value' => '1',
						),
						array(
							'field' => 'field_5bbb6b18b9fcc',
							'operator' => '==',
							'value' => 'estate',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'new_lines' => '',
			),
			array(
				'key' => 'field_5bd6df6ed1e44',
				'label' => 'недвиж ставка ДО',
				'name' => 'estate_stavka_do',
				'type' => 'number',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5bbb6b03b9fcb',
							'operator' => '==',
							'value' => '1',
						),
						array(
							'field' => 'field_5bbb6b18b9fcc',
							'operator' => '==',
							'value' => 'estate',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array(
				'key' => 'field_5bd6df6ad1e43',
				'label' => 'недвиж ставка ОТ',
				'name' => 'estate_stavka_ot',
				'type' => 'number',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5bbb6b03b9fcb',
							'operator' => '==',
							'value' => '1',
						),
						array(
							'field' => 'field_5bbb6b18b9fcc',
							'operator' => '==',
							'value' => 'estate',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array(
				'key' => 'field_5bd6df72d1e45',
				'label' => 'недвиж Сумма займа ОТ',
				'name' => 'estate_sum_ot',
				'type' => 'number',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5bbb6b03b9fcb',
							'operator' => '==',
							'value' => '1',
						),
						array(
							'field' => 'field_5bbb6b18b9fcc',
							'operator' => '==',
							'value' => 'estate',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => 'до',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array(
				'key' => 'field_5bd6dffad1e49',
				'label' => 'недвиж ставка ДО',
				'name' => 'estate_stavka_do',
				'type' => 'number',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5bbb6b03b9fcb',
							'operator' => '==',
							'value' => '1',
						),
						array(
							'field' => 'field_5bbb6b18b9fcc',
							'operator' => '==',
							'value' => 'estate',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array(
				'key' => 'field_5bd6df78d1e46',
				'label' => 'недвиж сумма	займа ДО',
				'name' => 'estate_sum_do',
				'type' => 'number',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5bbb6b03b9fcb',
							'operator' => '==',
							'value' => '1',
						),
						array(
							'field' => 'field_5bbb6b18b9fcc',
							'operator' => '==',
							'value' => 'estate',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => 'до',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array(
				'key' => 'field_5bd6df80d1e47',
				'label' => 'недвиж срок займа ОТ',
				'name' => 'estate_srok_ot',
				'type' => 'number',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5bbb6b03b9fcb',
							'operator' => '==',
							'value' => '1',
						),
						array(
							'field' => 'field_5bbb6b18b9fcc',
							'operator' => '==',
							'value' => 'estate',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => 'до',
				'append' => 'месяцев',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array(
				'key' => 'field_5bd6df85d1e48',
				'label' => 'недвиж срок займа ДО',
				'name' => 'estate_srok_do',
				'type' => 'number',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5bbb6b03b9fcb',
							'operator' => '==',
							'value' => '1',
						),
						array(
							'field' => 'field_5bbb6b18b9fcc',
							'operator' => '==',
							'value' => 'estate',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => 'до',
				'append' => 'месяцев',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array(
				'key' => 'field_5bbbcef41820c',
				'label' => 'Выкуп',
				'name' => 'avto_vikup',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5bbb6b03b9fcb',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_5bbcb3c0c51ea',
				'label' => 'Резюме',
				'name' => 'resume_card',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5bbcb2f3c51e9',
				'label' => 'Плюсы',
				'name' => 'plus',
				'type' => 'textarea',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => 10,
				'new_lines' => '',
			),
			array(
				'key' => 'field_5bbcb77326d9b',
				'label' => 'Минусы',
				'name' => 'minus',
				'type' => 'textarea',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => 10,
				'new_lines' => '',
			),
			array(
				'key' => 'field_5bbcd677c25b5',
				'label' => 'обновлено',
				'name' => 'upd',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'page',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'acf_after_title',
		'style' => 'seamless',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));

endif;